### ISSUE TITLE
Input the player key, but still got error "License not found"

### ISSUE THREAD

**Issue by serenavisualon** [bitmovin/bitmovin-player-windows-app-demo#2]
Hi 
I sign up a account on bitmovin website, and got keys from the account information, then input the key in "main.js", but the player still shows "License not found". I do not know what I should do next.

There are two keys:
key1: Organization Id
key2: Api Keys
I tried the two keys, but both failed.
"Input your player key into main.js", where can I get the player key exactly?

Thanks!

**Comment by LudoMichaud** [comment]
Hi @serenavisualon 
Thank you for getting in contact.
 
You can get the player key from your [Bitmovin Dashboard](https://bitmovin.com/dashboard/player/licenses) and paste it within your app at [this line](https://github.com/bitmovin/bitmovin-player-windows-app-demo/blob/master/BitmovinWindowsAppDemo/js/main.js#L7). In order to use the app, you would also have to whitelist your package name, as mentioned in the [Readme](https://github.com/bitmovin/bitmovin-player-windows-app-demo#notes-for-developing-your-own-app) of this sample app.
Please feel free to reach out to our support team at support@bitmovin.com in case you have further questions. 

Thanks
